import type { TrustSignalReport, Suggestion } from "../types.js";
import type { DetectedDecision } from "../analyzers/system_thinking/DecisionDetector.js";
import type { LlmClient } from "../llm/LlmClient.js";

export interface DraftContext {
  report: TrustSignalReport;
  diagramDraft: string | null;
  decisions: DetectedDecision[];
  llm?: LlmClient;
}

export async function enhanceWithLlm(
  draft: DraftResult,
  suggestion: Suggestion,
  ctx: DraftContext
): Promise<DraftResult> {
  if (!ctx.llm || !ctx.llm.available) return draft;
  const sys =
    "You are improving an engineer's portfolio documentation. Keep the user's edits intact " +
    "(anything between <!-- comments -->). Return ONLY the improved markdown.";
  const user = `Suggestion: ${suggestion.title}\n\nDraft to improve:\n\n${draft.content}`;
  try {
    const enhanced = await ctx.llm.complete({ systemPrompt: sys, userPrompt: user, maxTokens: 2000 });
    if (enhanced && enhanced !== "__IDE_BRIDGE__") return { ...draft, content: enhanced };
  } catch {/* fall through to original */}
  return draft;
}

export interface DraftResult {
  suggestionId: string;
  filename: string;
  content: string;
}

export function generateDraft(suggestion: Suggestion, ctx: DraftContext): DraftResult | null {
  const id = suggestion.id.split(".").pop()!;

  if (id === "ai_usage_doc" || id === "ai_transparency_section") return draftAiUsage(suggestion);
  if (id === "architecture_diagram_missing" || id === "no_architecture_diagram") {
    // Always draftable — fall back to a Mermaid stub when no diagram was
    // auto-derived, so the scan→apply handoff never dead-ends.
    const diagram = ctx.diagramDraft ?? STUB_DIAGRAM;
    return { suggestionId: suggestion.id, filename: "docs/architecture.md", content: archDoc(diagram) };
  }
  if (id === "adr_for_decisions" || id === "adr_backfill" || id === "adr_starter") return draftAdrs(suggestion, ctx);
  if (id === "deployment_proof") return draftDeploymentProof(suggestion);
  if (id === "postmortem_invitation") return draftPostmortem(suggestion);
  if (id === "add_usage_example") return draftUsageExample(suggestion);
  return null;
}

function draftAiUsage(s: Suggestion): DraftResult {
  const content = `# AI Usage

This project uses AI assistance. In 2026, transparent disclosure is more
credible than denial — this document is the disclosure.

## Where AI was used

<!-- List the parts of this codebase where AI assistance was used. Examples: -->
- *Initial scaffolding* of the test suite (drafts reviewed, names rewritten)
- *Boilerplate* for repetitive data-transformation utilities
- *Documentation drafts* (this file included), then edited for accuracy

## Where AI suggestions were overridden

<!-- List places where you rejected AI suggestions and explain why. -->
- *Authentication flow*: kept manual implementation because AI suggestion
  shipped tokens client-side; security tradeoff matters here
- *Database schema*: chose Postgres + a normalized schema over the AI-suggested
  document store; reasoning lives in \`docs/adr/0003-db-choice.md\`

## What was manually verified

- All security-sensitive paths (auth, input validation, secrets)
- Database migrations
- Production deployment configuration

---

*Generated by tucaken-signal v0.1 — edit before committing. Evidence basis:*
${s.evidenceBasis.map((e) => `- ${e.kind}${e.note ? `: ${e.note}` : ""}`).join("\n")}
`;
  return { suggestionId: s.id, filename: "AI_USAGE.md", content };
}

const STUB_DIAGRAM = `\`\`\`mermaid
graph TD
  A[Client] --> B[Entry point]
  B --> C[Core logic]
  C --> D[(Data store)]
\`\`\`

<!-- Replace the stub above with your actual topology. Nodes should be your
     real components: services, datastores, queues, external APIs. -->`;

function archDoc(diagram: string): string {
  return `# Architecture

${diagram}

## Notes

<!-- Replace these notes with the why behind the topology above. -->
- *Traffic ingress*: how requests reach the system
- *Persistence*: which datastores, why each
- *Operational concerns*: deploys, monitoring, on-call

*Auto-generated draft — verify accuracy before committing.*
`;
}

function draftAdrs(s: Suggestion, ctx: DraftContext): DraftResult {
  const lines: string[] = [];
  ctx.decisions.forEach((d, i) => {
    const n = String(i + 1).padStart(4, "0");
    lines.push(`## ${n}-${slug(d.topic)}.md`);
    lines.push("");
    lines.push(`# ${n}. ${d.topic}: chose ${d.chose}`);
    lines.push("");
    lines.push(`**Status:** accepted`);
    lines.push("");
    lines.push(`## Context`);
    lines.push(`<!-- Why was this decision needed? What constraints applied? -->`);
    lines.push("");
    lines.push(`## Decision`);
    lines.push(`Chose **${d.chose}** over ${d.over.join(", ")}.`);
    lines.push("");
    lines.push(`## Consequences`);
    lines.push(`<!-- What does this make easier? Harder? What did you give up? -->`);
    lines.push("");
    lines.push(`*Evidence:* \`${d.evidencePath}\``);
    lines.push("");
    lines.push("---");
    lines.push("");
  });
  return {
    suggestionId: s.id,
    filename: "docs/adr/ADRS-DRAFT.md",
    content: `# ADR drafts (split into separate files)\n\n${lines.join("\n")}`,
  };
}

function draftDeploymentProof(s: Suggestion): DraftResult {
  return {
    suggestionId: s.id,
    filename: "docs/deployment.md",
    content: `# Deployment

**Live:** <!-- https://your-app.example.com -->
**Status:** active
**Deployed via:** <!-- e.g. GitHub Actions → AWS via CDK -->

## Pipeline

1. Push to \`main\` triggers \`.github/workflows/deploy.yml\`
2. CI builds + tests
3. Deploy step provisions/updates infrastructure
4. Smoke checks confirm the live URL responds

## Observability

<!-- Link to Grafana dashboard / Datadog / Sentry, etc. -->

*Auto-generated draft.*
`,
  };
}

function draftPostmortem(s: Suggestion): DraftResult {
  return {
    suggestionId: s.id,
    filename: "docs/postmortems/0001-template.md",
    content: `# Postmortem: <incident title>

**Date:** <YYYY-MM-DD>
**Impact:** <users affected / duration>
**Severity:** <SEV-N>

## Summary
<2-3 sentence summary of what happened.>

## Timeline
- HH:MM — first signal
- HH:MM — escalated
- HH:MM — root cause identified
- HH:MM — mitigated
- HH:MM — resolved

## Root cause
<What actually went wrong, in plain prose.>

## What worked
<What systems / decisions held up.>

## What did not
<What systems / decisions failed and why.>

## Follow-ups
- [ ] <action>
- [ ] <action>
`,
  };
}

function draftUsageExample(s: Suggestion): DraftResult {
  return {
    suggestionId: s.id,
    filename: "README.usage-draft.md",
    content: `## Usage

\`\`\`ts
import { yourThing } from "your-package";

const result = await yourThing({ input: "example" });
console.log(result);
\`\`\`

<!-- Replace with the smallest useful example a consumer needs to evaluate adoption. -->
`,
  };
}

function slug(s: string): string { return s.toLowerCase().replace(/[^a-z0-9]+/g, "-"); }
